name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Cache deps
    - name: Permissions
      run: sudo chown -R $(whoami):$(id -ng) ~/.cargo/
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo-dir-${{ hashFiles('**/Cargo.lock') }}
        # restore-keys: |
        #   ${{ runner.os }}-cargo-
    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-target-
    - name: Build target
      run: ls -la target && ls -la target/debug
    - name: Build
      run: cargo build --bin remits
    - name: Build target
      run: ls -la target && ls -la target/debug
    - name: Fmt
      run: rustfmt --check --edition 2018 ./src/**/*.rs
    - name: Clippy
      run: rustup component add clippy && cargo clippy --all-targets -- -D warnings
    - name: Run server
      run: mkdir "$GITHUB_WORKSPACE/remits_test" && cargo run -- -d "$GITHUB_WORKSPACE/remits_test" &

    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      with:
        args: '-v --frozen --exclude-files src/bin/* src/bin/*/*'
    - name: tarpaulin target
      run: ls -la target && ls -la target/debug
    - name: Permissions
      run: sudo chown -R $(whoami):$(id -ng) ~/.cargo/