name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      id: cache
      with:
        path: target
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Build
      if: steps.cache.outputs.cache-hit != 'true'
      run: cargo build --bin remits --verbose
    - name: Fmt
      run: rustfmt --check --edition 2018 ./src/**/*.rs
    - name: Clippy
      run: rustup component add clippy && cargo clippy --all-targets -- -D warnings
    - name: Run server
      run: mkdir "$GITHUB_WORKSPACE/remits_test" && cargo run -- -d "$GITHUB_WORKSPACE/remits_test" &
    - name: Run tests
      run: cargo test --verbose
    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      with:
        args: '-v --exclude-files src/bin/* src/bin/*/*'
