name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --bin remits --verbose
    - name: Fmt
      run: rustfmt --check --edition 2018 ./src/**/*.rs
    - name: Clippy
      run: rustup component add clippy && cargo clippy --all-targets -- -D warnings
    - name: Run server
      run: mkdir "$GITHUB_WORKSPACE/remits_test" && cargo run -- -d "$GITHUB_WORKSPACE/remits_test" &
    - name: Run tests
      run: cargo test --verbose
    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
