name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Cache deps
    - name: Permissions
      run: sudo chown -R $(whoami):$(id -ng) ~/.cargo/
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo-directory-for-caching-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-directory-for-caching-
    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.os }}-normal-build-cache-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-normal-build-cache-
    - name: Cache tarpaulin deps
      uses: actions/cache@v1
      with:
        path: tarpaulin-out
        key: ${{ runner.os }}-tarpaulin-build-cache-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-tarpaulin-build-cache-

    - name: Build
      run: cargo build --bin remits
    - name: Fmt
      run: rustfmt --check --edition 2018 ./src/**/*.rs
    - name: Clippy
      run: rustup component add clippy && cargo clippy --all-targets -- -D warnings
    - name: Run server
      run: mkdir "$GITHUB_WORKSPACE/remits_test" && cargo run -- -d "$GITHUB_WORKSPACE/remits_test" &
    # Coverage
    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      with:
        args: '-v --frozen --target-dir tarpaulin-out/ --exclude-files src/bin/* src/bin/*/*'

    - name: Permissions
      run: sudo chown -R $(whoami):$(id -ng) ~/.cargo/